const cardImages = {
  'Spada-As': require('../assets/images/cards/Spada-As.jpg'),
  'Kopa-As': require('../assets/images/cards/Kopa-As.jpg'),
  'Dinar-As': require('../assets/images/cards/Dinar-As.jpg'),
  'Baston-As': require('../assets/images/cards/Baston-As.jpg'),
  'Spada-Trojka': require('../assets/images/cards/Spada-Trojka.jpg'),
  'Kopa-Trojka': require('../assets/images/cards/Kopa-Trojka.jpg'),
  'Dinar-Trojka': require('../assets/images/cards/Dinar-Trojka.jpg'),
  'Baston-Trojka': require('../assets/images/cards/Baston-Trojka.jpg'),
  'Spada-Kralj': require('../assets/images/cards/Spada-Kralj.jpg'),
  'Kopa-Kralj': require('../assets/images/cards/Kopa-Kralj.jpg'),
  'Dinar-Kralj': require('../assets/images/cards/Dinar-Kralj.jpg'),
  'Baston-Kralj': require('../assets/images/cards/Baston-Kralj.jpg'),
  'Spada-Kaval': require('../assets/images/cards/Spada-Kaval.jpg'),
  'Kopa-Kaval': require('../assets/images/cards/Kopa-Kaval.jpg'),
  'Dinar-Kaval': require('../assets/images/cards/Dinar-Kaval.jpg'),
  'Baston-Kaval': require('../assets/images/cards/Baston-Kaval.jpg'),
  'Spada-Fant': require('../assets/images/cards/Spada-Fant.jpg'),
  'Kopa-Fant': require('../assets/images/cards/Kopa-Fant.jpg'),
  'Dinar-Fant': require('../assets/images/cards/Dinar-Fant.jpg'),
  'Baston-Fant': require('../assets/images/cards/Baston-Fant.jpg'),
  'Spada-Sedemka': require('../assets/images/cards/Spada-Sedemka.jpg'),
  'Kopa-Sedemka': require('../assets/images/cards/Kopa-Sedemka.jpg'),
  'Dinar-Sedemka': require('../assets/images/cards/Dinar-Sedemka.jpg'),
  'Baston-Sedemka': require('../assets/images/cards/Baston-Sedemka.jpg'),
  'Spada-Sestka': require('../assets/images/cards/Spada-Sestka.jpg'),
  'Kopa-Sestka': require('../assets/images/cards/Kopa-Sestka.jpg'),
  'Dinar-Sestka': require('../assets/images/cards/Dinar-Sestka.jpg'),
  'Baston-Sestka': require('../assets/images/cards/Baston-Sestka.jpg'),
  'Spada-Petka': require('../assets/images/cards/Spada-Petka.jpg'),
  'Kopa-Petka': require('../assets/images/cards/Kopa-Petka.jpg'),
  'Dinar-Petka': require('../assets/images/cards/Dinar-Petka.jpg'),
  'Baston-Petka': require('../assets/images/cards/Baston-Petka.jpg'),
  'Spada-Stirka': require('../assets/images/cards/Spada-Stirka.jpg'),
  'Kopa-Stirka': require('../assets/images/cards/Kopa-Stirka.jpg'),
  'Dinar-Stirka': require('../assets/images/cards/Dinar-Stirka.jpg'),
  'Baston-Stirka': require('../assets/images/cards/Baston-Stirka.jpg'),
  'Spada-Dvojka': require('../assets/images/cards/Spada-Dvojka.jpg'),
  'Kopa-Dvojka': require('../assets/images/cards/Kopa-Dvojka.jpg'),
  'Dinar-Dvojka': require('../assets/images/cards/Dinar-Dvojka.jpg'),
  'Baston-Dvojka': require('../assets/images/cards/Baston-Dvojka.jpg'),
  'Zadnja-Stran': require('../assets/images/cards/Zadnja-Stran.png'),
};

export default cardImages;
