const cardImages = {
  'Spada-As': require('../assets/images/cards/Spada-As.png'),
  'Kopa-As': require('../assets/images/cards/Kopa-As.png'),
  'Dinar-As': require('../assets/images/cards/Dinar-As.png'),
  'Baston-As': require('../assets/images/cards/Baston-As.png'),
  'Spada-Trojka': require('../assets/images/cards/Spada-Trojka.png'),
  'Kopa-Trojka': require('../assets/images/cards/Kopa-Trojka.png'),
  'Dinar-Trojka': require('../assets/images/cards/Dinar-Trojka.png'),
  'Baston-Trojka': require('../assets/images/cards/Baston-Trojka.png'),
  'Spada-Kralj': require('../assets/images/cards/Spada-Kralj.png'),
  'Kopa-Kralj': require('../assets/images/cards/Kopa-Kralj.png'),
  'Dinar-Kralj': require('../assets/images/cards/Dinar-Kralj.png'),
  'Baston-Kralj': require('../assets/images/cards/Baston-Kralj.png'),
  'Spada-Kaval': require('../assets/images/cards/Spada-Kaval.png'),
  'Kopa-Kaval': require('../assets/images/cards/Kopa-Kaval.png'),
  'Dinar-Kaval': require('../assets/images/cards/Dinar-Kaval.png'),
  'Baston-Kaval': require('../assets/images/cards/Baston-Kaval.png'),
  'Spada-Fant': require('../assets/images/cards/Spada-Fant.png'),
  'Kopa-Fant': require('../assets/images/cards/Kopa-Fant.png'),
  'Dinar-Fant': require('../assets/images/cards/Dinar-Fant.png'),
  'Baston-Fant': require('../assets/images/cards/Baston-Fant.png'),
  'Spada-Sedemka': require('../assets/images/cards/Spada-Sedemka.png'),
  'Kopa-Sedemka': require('../assets/images/cards/Kopa-Sedemka.png'),
  'Dinar-Sedemka': require('../assets/images/cards/Dinar-Sedemka.png'),
  'Baston-Sedemka': require('../assets/images/cards/Baston-Sedemka.png'),
  'Spada-Sestka': require('../assets/images/cards/Spada-Sestka.png'),
  'Kopa-Sestka': require('../assets/images/cards/Kopa-Sestka.png'),
  'Dinar-Sestka': require('../assets/images/cards/Dinar-Sestka.png'),
  'Baston-Sestka': require('../assets/images/cards/Baston-Sestka.png'),
  'Spada-Petka': require('../assets/images/cards/Spada-Petka.png'),
  'Kopa-Petka': require('../assets/images/cards/Kopa-Petka.png'),
  'Dinar-Petka': require('../assets/images/cards/Dinar-Petka.png'),
  'Baston-Petka': require('../assets/images/cards/Baston-Petka.png'),
  'Spada-Stirka': require('../assets/images/cards/Spada-Stirka.png'),
  'Kopa-Stirka': require('../assets/images/cards/Kopa-Stirka.png'),
  'Dinar-Stirka': require('../assets/images/cards/Dinar-Stirka.png'),
  'Baston-Stirka': require('../assets/images/cards/Baston-Stirka.png'),
  'Spada-Dvojka': require('../assets/images/cards/Spada-Dvojka.png'),
  'Kopa-Dvojka': require('../assets/images/cards/Kopa-Dvojka.png'),
  'Dinar-Dvojka': require('../assets/images/cards/Dinar-Dvojka.png'),
  'Baston-Dvojka': require('../assets/images/cards/Baston-Dvojka.png'),
};

export default cardImages;
